---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2021/11/28 22:38
---

---@class AlbumController 相册控制器，传入两个gui，在初始化的时候会初始化CheckDetailController类
AlbumController = {albumGUI = nil , detailGUI = nil , slots = nil}

---构造器
---@param albumGUI userdata 相册GUI
---@param detailGUI userdata 详细GUI
function AlbumController:new(o,albumGUI,detailGUI)
    o = o or {}
    setmetatable(o,self)
    self.__index = self
    self.albumGUI = albumGUI
    self.detailGUI = detailGUI
    ---初始化CheckDetailController
    --TODO
    ---开始初始化slot
    self.slots = {}
    for _, v in ipairs(albumGUI:GetChildren()) do
        if v.ClassName == 'UIFigureObject' then
            if v:GetChild('SlotIndex') ~= nil then
                table.insert(self.slots,v)
            end
        end
    end
end

---保存照片到相册,传入待保存的照片的物体，去picture文件夹里查找该名，获得所有回溯形态，找到对应形态，将其克隆到GUI节点下。
---如果slot全部沾满，直接返回false，如果没找着（遇到bug）直接返回false
---@param objectName userdata 待保存的照片的物体
---@param recallIndex number 回溯的状态序号
---@return boolean 保存是否成功
function AlbumController:SavePic(objectName,recallIndex)
    local pictures = world.Resources.Picture
    ---从picture文件夹里查找此名称
    if pictures:GetChild(objectName) ~= nil then
        local targetFolder = pictures:GetChild(objectName)
        ---遍历所有recall的形态，判断值
        for _, picture in ipairs(targetFolder:GetChildren()) do
            if picture:GetChild('recallIndex') ~= nil then
                if picture:GetChild('recallIndex').Value == recallIndex then
                    ---遍历slot
                    for _, slot in ipairs(self.slots) do
                        ---@field canInsert boolean 是否能插入
                        local canInsert = true
                        ---寻找slot中是否有叫picture的节点
                        if slot:GetChild('Picture') ~= nil then
                            canInsert = false
                        end
                        ---如果没有这个节点，进行插入，将这个照片与子节点克隆到节点下
                        if canInsert then
                            local cloned = picture:Clone(slot,false)
                            ---改变尺寸，名字为物体名方便查找
                            cloned.Name = objectName
                            cloned.Size = Vector2(600,338)
                            return true
                        end
                    end
                end
            end
        end
    end
    return false
end

---@param slotValue number 待进入预览的slot的值
---@return void
function AlbumController:ToDetail(slotValue)

end

---重新调整相册，保持相册不留空，保证没有图片的空位是disconnect了ToDetail
---@return void
function AlbumController:Refresh()

end

