---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2021/12/3 15:25
---
PlayerController = require('Moudles/PlayerController')

InteractionController = {}

InteractionController.UI = world.Resources.UI.Mobius

InteractionController.slots = {}

InteractionController.tempFolder = world.Resources.UI.Temp

InteractionController.album = world.Resources.UI.Album

InteractionController.mobiusModel = world.Resources.Model.Mobius

InteractionController.dialogBoxBefore = world.DialogArea.Box

InteractionController.dialogBoxAfter = world.DialogArea.Mobius

InteractionController.notification = world.Resources.UI.tips.EOpenGUI

InteractionController.E_Key = Enum.KeyCode.E

InteractionController.openUI = function()
    if Input.GetPressKeyData(InteractionController.E_Key)>0 then
        InteractionController.UI:SetActive(true)
        PlayerController.AllowMove = false
        PlayerController:ChooseMode()
        PlayerController:SetInteractionOn(true)
    end
end

function InteractionController:Init()
    for _, child in ipairs(InteractionController.UI:GetChildren()) do
        if child.ClassName == 'UiFigureObject' then
            table.insert(InteractionController.slots,child)
        end
    end
    
    for i, v in ipairs(InteractionController.slots) do
        assert(v:GetChild('Btn'))
        v:GetChild('Btn').OnClick:Connect(function() InteractionController:Choose(i) end)
    end
    
    assert(InteractionController.UI:GetChild('VerifyBtn'))
    InteractionController.UI:GetChild('VerifyBtn').OnClick:Connect(function()
        
        for _, slot in ipairs(InteractionController.slots) do
            if slot:FindFirstChildByType('UiImageObject') == nil then
                return
            end
        end

        local slot1Name = InteractionController.slots[1]:FindFirstChildByType('UiImageObject').Name
        local slot2Name = InteractionController.slots[2]:FindFirstChildByType('UiImageObject').Name
        local slot3Name = InteractionController.slots[3]:FindFirstChildByType('UiImageObject').Name
        local slot4Name = InteractionController.slots[4]:FindFirstChildByType('UiImageObject').Name

        if slot2Name == 'BrokenNotebook' and slot3Name == 'Clothes' then
            if slot1Name == 'Slander1' then

                if slot4Name == 'Slander2' then
                    InteractionController:VerifySuccess()
                end

            elseif slot1Name == 'Slander2' then

                if slot4Name == 'Slander1' then
                    InteractionController:VerifySuccess()
                end

            end
        end

    end)

    local RightMouse_Key = Enum.KeyCode.Mouse1
    Input.OnKeyDown:Connect(function()
        if InteractionController.UI.ActiveSelf then
            if Input.GetPressKeyData(RightMouse_Key)>0 then
                InteractionController.UI:SetActive(false)
                PlayerController:SetDefault()
                PlayerController:SetInteractionOn(false)
            end
        end
    end)

    InteractionController.dialogBoxBefore.OnCollisionBegin:Connect(function(hitObject,hitPoint,hitNormal)
        if hitObject.ClassName =='PlayerInstance' then
            Input.OnKeyDown:Connect(InteractionController.openUI)
            InteractionController.notification:SetActive(true)
        end
    end)

    InteractionController.dialogBoxBefore.OnCollisionEnd:Connect(function(hitObject,hitPoint,hitNormal)
        if hitObject.ClassName =='PlayerInstance' then
            Input.OnKeyDown:Disconnect(InteractionController.openUI)
            InteractionController.notification:SetActive(false)
        end
    end)


end

function InteractionController:VerifySuccess()
    print('verify success')
    PlayerController:SetDefault()
    PlayerController:SetInteractionOn(false)
    InteractionController.mobiusModel:SetActive(true)
    InteractionController.UI:SetActive(false)
    InteractionController.dialogBoxBefore:SetActive(false)
    InteractionController.dialogBoxAfter:SetActive(true)
    world.Resources.UI.tips.F:SetActive(false)
    Input.OnKeyDown:Disconnect(InteractionController.openUI)
    InteractionController.notification:SetActive(false)

end

function InteractionController:Choose(slotIndex)
    assert(InteractionController.slots[slotIndex])
    ---复制一份album到临时文件夹
    local cloned = InteractionController.album:Clone(InteractionController.tempFolder,false)
    ---重新初始化按钮
    local albumSlot = {}

    for _, child in ipairs(cloned:GetChildren()) do
        if child.ClassName ==  'UiFigureObject' then
            table.insert(albumSlot,child)
        end
    end

    for _,slot in ipairs(albumSlot) do
	
        if slot:FindFirstChildByType('UiImageObject') ~= nil then

            slot:GetChild('CheckDetailBtn').OnClick:Connect(function()
			
                ---删除slot内照片，并将将照片复制到slot
                while InteractionController.slots[slotIndex]:FindFirstChildByType('UiImageObject') ~=nil do
                    InteractionController.slots[slotIndex]:FindFirstChildByType('UiImageObject'):Destroy()
                end
				
				local pic = slot:FindFirstChildByType('UiImageObject')
				local targetSlot = InteractionController.slots[slotIndex]

				--UiFigureObject : Workspace.Resources.UI.Mobius.Slot1
				--print(targetSlot.ClassName..' : '..targetSlot.PathToWorld)
				--UiImageObject : Workspace.Resources.UI.Temp.Album.Slot1.PaperCrane
				--print(pic.ClassName..' : '..pic.PathToWorld)
				
				local clonedPic = pic:Clone(targetSlot,false) --nil?
				
                clonedPic:Up()
                cloned:SetActive(false)
                InteractionController.UI:SetActive(true)
                cloned:Destroy()
            end)

        end
    end

    assert(cloned:GetChild('Title'))
    cloned:GetChild('Title').Text = '请选择一张照片'

    assert(cloned:GetChild('BackBtn'))
    cloned:GetChild('BackBtn').OnClick:Connect(function()
        cloned:SetActive(false)
        InteractionController.UI:SetActive(true)
		cloned:Destroy()
    end)
	
	InteractionController.UI:SetActive(false)
	cloned:SetActive(true)

end

return InteractionController