---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2021/12/2 21:24
---
PlayerController = {}

PlayerController.mainCamera = world.Local.MainCamera
PlayerController.AllowMove = true
PlayerController.CameraOn = false
PlayerController.AlbumOn = false
PlayerController.DialogOn = false
PlayerController.InteractionOn = false
PlayerController.BlackOn = false



function PlayerController:Init()
    PlayerController.CameraOn = false
end

function PlayerController:ChooseMode()
    PlayerController.mainCamera.EnableMouseDrag = false
    PlayerController.mainCamera.CursorDisplay = true
    PlayerController.mainCamera.CursorLock = false
end

function PlayerController:SetDefault()
    PlayerController.mainCamera.EnableMouseDrag = true
    PlayerController.mainCamera.CursorDisplay = false
    PlayerController.mainCamera.CursorLock = true
    PlayerController.AllowMove = true
end

function PlayerController:SetCameraOn(bool)
    PlayerController.CameraOn = bool
end

function PlayerController:IsCameraOn()
    return PlayerController.CameraOn
end

function PlayerController:SetAlbumOn(bool)
    PlayerController.AlbumOn = bool
end

function PlayerController:IsAlbumOn()
    return PlayerController.AlbumOn
end

function PlayerController:SetDialogOn(bool)
    PlayerController.DialogOn = bool
end

function PlayerController:IsDialogOn()
    return PlayerController.DialogOn
end

function PlayerController:SetInteractionOn(bool)
    PlayerController.InteractionOn = bool
end

function PlayerController:IsInteractionOn()
    return PlayerController.InteractionOn
end

function PlayerController:SetBlackOn(bool)
    PlayerController.BlackOn = bool
end

function PlayerController:IsBlackOnOn()
    return PlayerController.BlackOn
end

return PlayerController