---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2021/11/29 22:06
---
---@class Utils static class，工具类
Utils = {}

---得到某个表的子表
---@param table table 待操作的表
---@param from number 从哪个开始
---@param to number 到那个结束
---@return table 从from到to的子表
function Utils.GetSubTable(targetTable,from,to)
    return table.pack(table.unpack(targetTable,from,to))
end

return Utils